version: '3.4'

services:

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
       - MONGO_INITDB_ROOT_USERNAME=admin
       - MONGO_INITDB_ROOT_PASSWORD=changeit

  eventstore:
    image: 'eventstore/eventstore:latest'
    container_name: eventstore
    ports:
      - "2113:2113"
      - "1113:1113"

  consul:
    image: 'consul'
    container_name: consul
    ports:
      - "8500:8500"

  authentication:
    image: ${DOCKER_REGISTRY-azureplayground.azurecr.io}/azureplayground.authentication:${VERSION_TAG:-latest}
    build: 
      context: .
      dockerfile: ./AzurePlayground.Authentication/Dockerfile
    container_name: authentication
    depends_on:
      - mongo
    environment:
      - serviceConfiguration:mongoConnectionString=${AZUREPLAYGROUND_MONGO_CONNECTION_STRING}
      - serviceConfiguration:identity=${AZUREPLAYGROUND_AUTHENTICATION_URL}
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443

  gateway:
    image: ${DOCKER_REGISTRY-azureplayground.azurecr.io}/azureplayground.gateway:${VERSION_TAG:-latest}
    build:
      context: .
      dockerfile: ./AzurePlayground.Gateway/Dockerfile
    container_name: gateway
    depends_on:
      - consul
      - eventstore
      - authentication
    environment:
      - GlobalConfiguration:RequestIdKey=OcRequestId
      - GlobalConfiguration:ServiceDiscoveryProvider:Host=consul
      - GlobalConfiguration:ServiceDiscoveryProvider:Port=8500
      - GlobalConfiguration:ServiceDiscoveryProvider:Type=Consul
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443

  app:
    image: ${DOCKER_REGISTRY-azureplayground.azurecr.io}/azureplayground.web.app:${VERSION_TAG:-latest}
    build:
      context: .
      dockerfile: ./AzurePlayground.Web.App/Dockerfile
    container_name: app
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      - serviceConfiguration:gateway=${AZUREPLAYGROUND_GATEWAY_URL}
      - serviceConfiguration:identity=${AZUREPLAYGROUND_AUTHENTICATION_URL}

  compliance:
    image: ${DOCKER_REGISTRY-azureplayground.azurecr.io}/azureplayground.compliance.service:${VERSION_TAG:-latest}
    build:
      context: .
      dockerfile: ./AzurePlayground.Compliance.Service/Dockerfile
    container_name: compliance
    depends_on:
      - gateway
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      - serviceConfiguration:identity=${AZUREPLAYGROUND_AUTHENTICATION_URL}
      - serviceConfiguration:consul=${AZUREPLAYGROUND_CONSUL_URL}
      - serviceConfiguration:eventstore=${AZUREPLAYGROUND_EVENTSTORE_CONNECTION_STRING}
      - serviceConfiguration:id=compliance

  market:
    image: ${DOCKER_REGISTRY-azureplayground.azurecr.io}/azureplayground.market.service:${VERSION_TAG:-latest}
    build: 
      context: .
      dockerfile: ./AzurePlayground.Market.Service/Dockerfile
    container_name: market
    depends_on:
      - gateway
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      - serviceConfiguration:gateway=${AZUREPLAYGROUND_GATEWAY_URL}
      - serviceConfiguration:identity=${AZUREPLAYGROUND_AUTHENTICATION_URL}
      - serviceConfiguration:consul=${AZUREPLAYGROUND_CONSUL_URL}
      - serviceConfiguration:eventstore=${AZUREPLAYGROUND_EVENTSTORE_CONNECTION_STRING}
      - serviceConfiguration:id=market

  trade:
    image: ${DOCKER_REGISTRY-azureplayground.azurecr.io}/azureplayground.trade.service:${VERSION_TAG:-latest}
    build:
      context: .
      dockerfile: ./AzurePlayground.Trade.Service/Dockerfile
    container_name: trade
    depends_on:
      - gateway
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      - serviceConfiguration:identity=${AZUREPLAYGROUND_AUTHENTICATION_URL}
      - serviceConfiguration:consul=${AZUREPLAYGROUND_CONSUL_URL}
      - serviceConfiguration:eventstore=${AZUREPLAYGROUND_EVENTSTORE_CONNECTION_STRING}
      - serviceConfiguration:id=trade

  price:
    image: ${DOCKER_REGISTRY-azureplayground.azurecr.io}/azureplayground.price.service:${VERSION_TAG:-latest}
    build: 
      context: .
      dockerfile: ./AzurePlayground.Price.Service/Dockerfile
    container_name: price
    depends_on:
      - gateway
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      - serviceConfiguration:identity=${AZUREPLAYGROUND_AUTHENTICATION_URL}
      - serviceConfiguration:consul=${AZUREPLAYGROUND_CONSUL_URL}
      - serviceConfiguration:hubs=${AZUREPLAYGROUND_PRICE_HUBS}
      - serviceConfiguration:id=price

  event:
    image: ${DOCKER_REGISTRY-azureplayground.azurecr.io}/azureplayground.trade.event.service:${VERSION_TAG:-latest}
    build: 
      context: .
      dockerfile: ./AzurePlayground.Trade.Event.Service/Dockerfile
    container_name: event
    depends_on:
      - gateway
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      - serviceConfiguration:identity=${AZUREPLAYGROUND_AUTHENTICATION_URL}
      - serviceConfiguration:consul=${AZUREPLAYGROUND_CONSUL_URL}
      - serviceConfiguration:eventstore=${AZUREPLAYGROUND_EVENTSTORE_CONNECTION_STRING}
      - serviceConfiguration:hubs=${AZUREPLAYGROUND_TRADE_EVENT_HUBS}
      - serviceConfiguration:id=event

  generator:
    image: ${DOCKER_REGISTRY-azureplayground.azurecr.io}/azureplayground.trade.generator:${VERSION_TAG:-latest}
    build: 
     context: .
     dockerfile: ./AzurePlayground.Trade.Generator/Dockerfile
    container_name: generator
    depends_on:
      - trade
      - market
      - compliance
    environment:
      - serviceConfiguration:gateway=${AZUREPLAYGROUND_GATEWAY_URL}
      - serviceConfiguration:identity=${AZUREPLAYGROUND_AUTHENTICATION_URL}
      - serviceConfiguration:eventstore=${AZUREPLAYGROUND_EVENTSTORE_CONNECTION_STRING}



