version: '3.4'

services:

  authentication:
    image: ${DOCKER_REGISTRY-}azureplaygroundauthentication
    build: ./AzurePlayground.Authentication
    restart: always
    container_name: authentication
    ports:
      - "5001:5001"
    expose:
      - "5001"
    environment:
      - ASPNETCORE_URLS=http://*:5001
      - serviceConfiguration:mongoConnectionString=mongodb://mongo:27017
      - serviceConfiguration:mongoDatabase=playground
      - serviceConfiguration:identity=http://authentication:5001
    depends_on:
      - mongo

  trades:
    image: ${DOCKER_REGISTRY-}azureplaygroundtradeservice
    build: ./AzurePlayground.Trade.Service
    container_name: trades
    ports:
      - "5000:5000"    expose:
      - "5000"    environment:
      - ASPNETCORE_URLS=http://*:5000
      - serviceConfiguration:identity=http://authentication:5001

  app:
    image: ${DOCKER_REGISTRY-}azureplaygroundwebapp
    build: ./AzurePlayground.Web.App
    container_name: app
    ports:
      - "5002:5002"
    expose:
      - "5002"
    environment:
      - ASPNETCORE_URLS=http://*:5002
      - serviceConfiguration:identity=http://authentication:5001

  mongo:
    image: 'bitnami/mongodb:latest'
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"