FROM microsoft/dotnet:2.2-sdk
COPY ./bin/publish /app
WORKDIR /app

RUN cp -a ./certs/. /usr/local/share/ca-certificates/
RUN update-ca-certificates
ENV ASPNETCORE_Kestrel__Certificates__Default__Path app.pfx

ENTRYPOINT ["dotnet", "AzurePlayground.Web.App.dll"]
